version: 0.2
phases:
 install:
	runtime-versions:
         php: 7.4
         nodejs: 12.x
   commands:
     - |
 	 sudo yum update -y
         sudo yum install -y libpq-dev libzip-dev
         sudo yum --enablerepo=remi,epel install php openssl php-common php-curl php-json php-zip php-mysql php-mcrypt php-xml php-mbstring
         sudo php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
         sudo php composer-setup.php ;
         sudo php -r "unlink('composer-setup.php');" ;
         sudo mv composer.phar /usr/local/bin/composer

         #Various handy node based dev tools - do you need these during your build? Comment if not.
         #npm install -g gulp
         #npm install -g grunt
         #npm install -g webpack

 build:
   commands:
     - composer install
     - php artisan migrate 

 post_build:
   commands:
     - echo Build completed on `date`
     # Do you need to do this? In many cases phpunit will use sqlite or similar to avoid the need for a real DB.
     # If you don't need it delete it
     # - /usr/bin/mysql  -u root -e "GRANT ALL ON *.* TO 'test'@'localhost' IDENTIFIED BY '' WITH GRANT OPTION"
     # - mysqladmin -u test create test
     # - mysqladmin -u test create test
     - ./vendor/bin/phpunit